name: Python Swap Program

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  run-swap-program:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Python dependencies (if any)
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip

      # Step 4: Run the Python script
      - name: Run python swap program
        run: |
          python <<EOF
          # Define two numbers
          num1 = 10
          num2 = 20

          # Call the function and display the result
          print(f"Before swapping: num1 = {num1}, num2 = {num2}")

          # Swap the numbers
          num1, num2 = num2, num1

          print(f"After swapping: num1 = {num1}, num2 = {num2}")
          EOF
