name: Run Python Script
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  run-python-script:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
 
      # Step 3: Upgrade pip (if required)
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
 
      # Step 4: Run Python script
      - name: Run Python Script
        run: |
          # Function to add two numbers
          def add_numbers(a, b):
              return a + b
 
          # Define two numbers
          num1 = 10
          num2 = 20
 
          # Call the function and display the result
          result = add_numbers(num1, num2)
          print(f"The sum of {num1} and {num2} is {result}.")
